### ISSUE TITLE
Configurable keymap

### ISSUE THREAD

**Issue by arthurlutz** [Dhole/CopperBoy#4]
After compiling it for the gameshell clockworkpi (see #3 ) I'll probably try to use the libretro version. But using the "normal" version it would be nice to be able to configure a keymap when using a different keyset.

**Comment by Dhole** [comment]
I will leave the sdl frontend as is, without introducing any feature in order to have it as a minimal functioning fronted.  For more frontend features, as you say, there's the libretro version.
